services:
  - type: web
    name: hiyari_3
    env: python
    plan: free  # プランによって変更してください
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn hiyarihatto.wsgi --log-file -"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hiyari_db  # 作成したPostgreSQLデータベースの名前
          property: connectionString
      - key: SECRET_KEY
        sync: false
    autoDeploy: true
